name: update_robottelo_image

on: [push]

jobs:
  robottelo_container:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Get image tag
        id: image_tag
        run: |
          echo -n ::set-output name=IMAGE_TAG::
          TAG="${GITHUB_REF##*/}"
          if [ "${TAG}" == "master" ]; then
              TAG="latest"
          fi
          echo "${TAG}"
      - name: Test
        run: echo "${{ steps.image_tag.outputs.IMAGE_TAG }}"
