name: Create and push Robottelo container image to Quay.

on:
  push:
    branches: master

jobs:
  robottelo_container:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
